### ISSUE TITLE
cannot create release for python package

### ISSUE THREAD

**Issue by builder555** [ahmadnassri/action-semantic-release#186]
## Steps to reproduce:

1. Create a new repo
2. Add example to .github/workflows/ci.yml:
    ```yml
    on:
      push:
        branches: [ master ]
    
    jobs:
      release:
        runs-on: ubuntu-latest
    
        steps:
          - name: checkout
            uses: actions/checkout@v4
    
          - name: semantic-release
            uses: ahmadnassri/action-semantic-release@v2
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    ```
3. Set permissions on repo to allow R&W for actions
4. Add a hello-world example in main.py
5. commit & push

## Expected results:

Created 0.1.0 release

## Actual results:

Error: SemanticReleaseError: Missing `package.json` file

## Other:

Since this is a python package, it shouldn't try to publish to NPM or search for package.json file.

https://github.com/builder555/blah/actions/runs/7396822456
